// export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
// export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
export const REQUEST_LOGIN_USER = 'REQUEST_LOGIN_USER';
export const RECEIVE_LOGIN_USER = 'RECEIVE_LOGIN_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const REQUEST_CLASSES = 'REQUEST_CLASSES';
export const RECEIVE_CLASSES = 'RECEIVE_CLASSES';
